---

- name: Install HTTP server
  apk: 
    name: lighttpd
    state: present

- name: Install additional tools
  apk: 
    name: tar
    state: present

- name: Verify the PXE data directory
  stat:
    path: /var/www/configs
  register: datadir
    
- name: Create missing directories
  file:
    path: /var/www/configs
    state: directory
    mode: 0777
    group: lighttpd
    owner: lighttpd
  when: not datadir.stat.exists
    
- name: Create configurations directories
  file:
    path: /var/www/configs
    state: directory
    mode: 0777
    group: lighttpd
    owner: lighttpd
  when: not datadir.stat.exists

- name: Configure HTTP service
  template:
    src: lighttpd.conf.j2    
    dest: "/etc/lighttpd/lighttpd.conf"
    owner: root
    group: root 
    mode: 0644
    
- name: Restart HTTP service
  service:
    name: "lighttpd"
    state: restarted
    enabled: true    

- name: Create the profiles save script
  template:
    src: save-config.sh.j2
    dest: /var/www/configs/save-config.sh
    mode: 0750
    owner: lighttpd
    group: lighttpd

#- name: Setup the XL configuration files
#  include_tasks: xl.yml