---

- name: Vérification du répertoire de travail
  stat:
    path: "~/alpine-rpi-{{ alpine_version }}-aarch64"
  register: rep_donnees
    
- name: Contrôle du répertoire de travail
  debug:
    msg: "Le répertoire existe"
  when: rep_donnees.stat.exists
  
- name: Création du répertoire de travail
  file:
    path: "~/alpine-rpi-{{ alpine_version }}-aarch64"
    state: directory
    mode: 0650
  when: not rep_donnees.stat.exists

- name: rPi4 - Téléchargement et décompression de l'archive de boot 
  unarchive:
    src: "{{ depot_noyaux }}/alpine-rpi-{{ alpine_version }}-aarch64.tar.gz"
    dest: "~/alpine-rpi-{{ alpine_version }}-aarch64"
    mode: 0650
    remote_src: yes

- name: rPi4 - Copie du fichier modloop
  copy:
    src: ~/alpine-rpi-{{ alpine_version }}-aarch64/boot/modloop-rpi4
    dest: /var/www/pxe/modloop-rpi4
    mode: 0650
    owner: lighttpd
    group: lighttpd
    remote_src: yes

- name: rPi4 - Nettoyage des fichiers
  file:
    path: "~/alpine-rpi-{{ alpine_version }}-aarch64"
    state: absent