---

- name: Récupération du noyau pour le boot PXE
  get_url:
    url: "{{depot_noyaux}}vmlinuz-lts"
    dest: /var/www/pxe
    mode: 0650
    owner: lighttpd
    group: lighttpd
    
- name: Récupération du modloop pour le boot PXE
  get_url:
    url: "{{depot_noyaux}}modloop-lts"
    dest: /var/www/pxe
    mode: 0650
    owner: lighttpd
    group: lighttpd
    
- name: Récupération du initramfs pour le boot PXE
  get_url:
    url: "{{depot_noyaux}}initramfs-lts"
    dest: /var/www/pxe
    mode: 0650
    owner: lighttpd
    group: lighttpd
    
- name: Création du script PXE pour le boot
  template:
    src: gpxe-script.j2
    dest: /var/www/pxe/gpxe-script
    mode: 0750
    owner: lighttpd
    group: lighttpd