services:
  repository:
    image: coatldev/devpi
    container_name: devpi
    ports: ["3141:3141"]
    environment:
      - DEVPI_PASSWORD=devpi
    volumes:
      - /Users/tristanisrael/Documents/Depots/Python:/data
    restart: unless-stopped

