permit nopass svc-orchestrator as root cmd /usr/sbin/xl
permit nopass svc-orchestrator as root cmd /usr/bin/xenstore-read
permit nopass svc-orchestrator as root cmd /usr/lib/safecor/bin/start-sys-usb.sh
permit nopass svc-orchestrator as root cmd /usr/lib/safecor/bin/start-sys-gui.sh
permit nopass svc-orchestrator as root cmd /usr/lib/safecor/bin/start-business-domain.sh
