# Filter on  "Safecor/"
filter f_safecor {
    program("^Safecor/");
};

# Log file
destination d_safecor {
    file("/var/log/safecor/system.log"
         create-dirs(yes)
         owner(nobody)
         group(safecor)
         perm(0640)
         template(t_file)
        );
};

# Log path
log {
    source(s_sys);
    filter(f_safecor);
    destination(d_safecor);
};