---

- name: Install the FTP client
  apk:
    name: chrony
    state: present

- name: Configure the NTP
  template:
    src: chrony.conf.j2
    dest: "/etc/chrony/chrony.conf"
    mode: 00644750
    owner: root
    group: root

- name: Restart the NTP
  service:
    name: "chronyd"
    state: restarted
    enabled: true    