---

- name: Configuration du client NTP Chrony
  template:
    src: chrony.conf.j2
    dest: "/etc/chrony/chrony.conf"
    mode: 00644750
    owner: root
    group: root

- name: Redémarrage du service chronyd
  service:
    name: "chronyd"
    state: restarted
    enabled: true    