---
 
- name: Installation du serveur TFTP 
  apk: 
    name: tftp-hpa
    state: present

- name: Vérification du répertoire de données PXE
  stat:
    path: /var/tftpboot/pxe
  register: rep_donnees

- name: Modification des permissions sur le dossier tftpboot
  file:
    path: /var/tftpboot
    mode: 0755
    
- name: Contrôle du répertoire de données
  debug:
    msg: "Le répertoire existe"
  when: rep_donnees.stat.exists
  
- name: Création du répertoire de données PXE
  file:
    path: /var/tftpboot/pxe
    state: directory
    mode: 0755    
  #when: not rep_donnees.stat.exists   

- name: Installation de la configuration S Raspberry Pi 4B
  include_tasks: s_raspi_4b.yml
  when: configurations.s_raspi_4b|bool

- name: Installation de la configuration XL 
  include_tasks: xl.yml
  when: configurations.xl|bool

- name: Redémarrage du service
  service:
    name: "in.tftpd"
    state: restarted
    enabled: true    
    