---

- name: "Install DHCP server for PXE boot"
  hosts: dhcp_host
  become: yes
  become_user: root
  
  roles:
    - role: deploy-dhcp-server
      when: install_dhcp | bool

- name: "Install TFTP server for PXE boot"
  hosts: tftp_host
  become: yes
  become_user: root
  
  roles:
    - role: deploy-tftp-server
      when: install_tftp | bool

- name: "Install HTTP server for PXE boot"
  hosts: http_host
  become: yes
  become_user: root
  
  roles:
    - role: deploy-http-server
      when: install_http | bool

- name: "Install NFS server for PXE boot"
  hosts: nfs_host
  become: yes
  become_user: root 
  roles:
    - role: deploy-nfs-server
      when: install_nfs | bool 

- name: "Configure NTP on all servers"
  hosts: all:!localhost
  become: yes
  become_user: root

  roles:
    - role: configure-ntp-client

#- name: "Verify the setup"
#  hosts: 127.0.0.1
#  become: yes
#  become_user: root
#
#  roles: 
#    - validate-infra
