all:
  vars:    
    install_dhcp: yes     
    install_tftp: yes     
    install_http: yes
    install_nfs: yes
    alpine_repository: "http://192.168.10.5/alpine/v3.21"
    safecor_repository: "http://192.168.10.5/safecor"
    alpine_kernels_server: "192.168.10.5"
    alpine_kernels_path: "/alpine/releases"
    alpine_version: "3.21.3"
    dhcp_domain: safecor.lan    
    lan_subnet: 192.168.10.0
    lan_netmask: 255.255.255.0
    lan_ip_start: 192.168.10.10
    lan_ip_end: 192.168.10.253
    lan_ip_broadcast: 192.168.10.255
    http_server: 192.168.10.1
    nfs_server: 192.168.10.1
    tftp_server: 192.168.10.1
    dhcp_server: 192.168.10.1
    ntp_server: 192.168.10.1
      
dhcp_host:
  hosts:
    192.168.10.1:
      ansible_user: "ansible"
      ansible_password: "ansible"    

http_host:
  hosts:
    192.168.10.1:
      ansible_user: "ansible"
      ansible_password: "ansible"

nfs_host:
  hosts:
    192.168.10.1:
      ansible_user: "ansible"
      ansible_password: "ansible"

tftp_host:
  hosts:
    192.168.10.1:
      ansible_user: "ansible"
      ansible_password: "ansible"