---

- name: Installation du serveur NFS
  apk:
    name: nfs-utils
    state: present

- name: Configuration du service
  template:
    src: exports.j2
    dest: "/etc/exports"
    mode: 0750
    
- name: Redémarrage du service NFS
  service:
    name: "nfs"
    state: restarted
    enabled: true
    
