--- 

- name: Install test tools
  apk:
    name: 
      - dhcpcd
      - tftp-hpa
    state: present

- name: Verify DHCP server configuration
  block:
    - name: Ask for an IP address
      shell: dhcpcd -T eth0 > /tmp/out.txt
      register: output     

    - name: Verify the emitter
      lineinfile:
        path: /tmp/out.txt 
        line: "new_dhcp_server_identifier='{{ dhcp_server }}'"
        state: present   
      check_mode: yes
      register: conf
      failed_when: (conf is changed) or (conf is failed)

    - name: Verify the PXE boot information
      lineinfile:
        path: /tmp/out.txt 
        line: "new_filename='gpxe.kpxe'"
        state: present   
      check_mode: yes
      register: conf
      failed_when: (conf is changed) or (conf is failed)
    
- name: Verify the TFTP address of the iPXE kernel
  debug:
    msg: "This check is not implemented yet"

- name: Verify the iPXE kernel download
  block:
    - name: Nettoyage
      file:
        path: gpxe.kpxe
        state: absent
    - name: Download
      shell: tftp {{ tftp_server }} -c get gpxe.kpxe      
    - name: Verify
      block:
        - stat: 
            path: gpxe.kpxe
          register: out        
        - fail: 
            msg: "The iPXE kernel file has not been found"
          when: (not out.stat.exists) or (out.stat.size == 0) 
    - name: Clean
      file:
        path: gpxe.kpxe
        state: absent      

- name: Verify the gpxe script download 
  block:
    - name: Download
      get_url: 
        url: http://{{ http_server }}/gpxe-script
        dest: /tmp/gpxe-script
    - name: Verify
      block:
        - stat: 
            path: /tmp/gpxe-script
          register: out        
        - fail: 
            msg: "The gpxe script is incorrect"
          when: (not out.stat.exists) or (out.stat.size == 0) 
    - file:
        path: /tmp/gpxe-script
        state: absent

- name: Verify the download of vmlinuz-virt
  debug:
    msg: Non implemented yet

- name: Verify the download of modloop-virt
  debug:
    msg: Non implemented yet

- name: Verify the download of initramfs-virt
  debug:
    msg: Non implemented yet
    