--- 

- name: Installation des outils de test
  apk:
    name: 
      - dhcpcd
      - tftp-hpa
    state: present

- name: Vérification du fonctionnement du serveur DHCP
  block:
    - name: Demande d'une adresse IP au serveur DHCP
      shell: dhcpcd -T eth0 > /tmp/out.txt
      register: output     

    - name: Vérification du serveur émetteur
      lineinfile:
        path: /tmp/out.txt 
        line: "new_dhcp_server_identifier='{{ dhcp_server }}'"
        state: present   
      check_mode: yes
      register: conf
      failed_when: (conf is changed) or (conf is failed)

    - name: Vérification des informations de boot PXE 
      lineinfile:
        path: /tmp/out.txt 
        line: "new_filename='gpxe.kpxe'"
        state: present   
      check_mode: yes
      register: conf
      failed_when: (conf is changed) or (conf is failed)
    
- name: Vérification de l'obtention de l'adresse TFTP du noyau iPXE 
  debug:
    msg: "Cette vérification n'est pas encore implémentée"

- name: Vérification du téléchargement du noyau iPXE
  block:
    - name: Nettoyage
      file:
        path: gpxe.kpxe
        state: absent
    - name: Téléchargement
      shell: tftp {{ tftp_server }} -c get gpxe.kpxe      
    - name: Vérification
      block:
        - stat: 
            path: gpxe.kpxe
          register: out        
        - fail: 
            msg: "Le fichier de noyau iPXE n'a pas été trouvé"
          when: (not out.stat.exists) or (out.stat.size == 0) 
    - name: Nettoyage
      file:
        path: gpxe.kpxe
        state: absent      

- name: Vérification du téléchargement du script gpxe 
  block:
    - get_url: 
        url: http://{{ http_server }}/gpxe-script
        dest: /tmp/gpxe-script
    - name: Vérification
      block:
        - stat: 
            path: /tmp/gpxe-script
          register: out        
        - fail: 
            msg: "Le fichier de script gpxe est incorrect"
          when: (not out.stat.exists) or (out.stat.size == 0) 
    - file:
        path: /tmp/gpxe-script
        state: absent

- name: Vérification du téléchargement du fichier vmlinuz-virt
  debug:
    msg: Action non implémentée

- name: Vérification du téléchargement du fichier modloop-virt
  debug:
    msg: Action non implémentée

- name: Vérification du téléchargement du fichier initramfs-virt
  debug:
    msg: Action non implémentée
    