# Run with $  docker-compose -f docker-compose.yml --profile network_boot --env-file safecor.env up
services:
  # The repository should be created first because we need the packages to build
  # the custom dnsmasq image for DHCP
  repository:
    image: httpd:2.4
    volumes:
      - ${LOCAL_REPOSITORY_PATH}:/var/www/html
      - ./conf/repository.conf:/etc/apache2/conf/extra/repository.conf
    ports: ["${REPOSITORY_WEB_PORT}:80"]
    restart: unless-stopped
    command: >
      sh -c "
      echo 'Include /etc/apache2/conf/extra/repository.conf' >> /usr/local/apache2/conf/httpd.conf &&
      httpd-foreground
      "
    networks: 
      - safecor

    # The repository is created for all profiles
    profiles: 
      - network_boot
      - offline
      - local_cache
      - dev

  devpi:
    image: coatldev/devpi
    container_name: devpi
    ports: ["3141:3141"]
    environment:
      - DEVPI_PASSWORD=devpi
    volumes:
      - /Users/tristanisrael/Documents/Depots/Python:/data
    restart: unless-stopped
    networks: 
      - safecor
    profiles: 
      - dev

networks:
  safecor:
