---

- name: Installation de GNU tar
  apk: 
    name: tar
    state: present

- name: rPi4 - Téléchargement et décompression de l'archive de boot 
  unarchive:
    src: "{{ depot_noyaux }}/alpine-rpi-{{ alpine_version }}-aarch64.tar.gz"
    dest: /var/tftpboot
    mode: 0744
    remote_src: yes

- name: rPi4 - Suppression des fichiers non raspi 4B
  file:
    path: "{{ item.name }}"
    state: absent
  with_items:
    - { name: /var/tftpboot/boot/config-rpi }
    - { name: /var/tftpboot/boot/initramfs-rpi }
    - { name: /var/tftpboot/boot/modloop-rpi }
    - { name: /var/tftpboot/boot/System.map-rpi }
    - { name: /var/tftpboot/boot/vmlinuz-rpi }    

- name: rPi4 - Installation du fichier config.txt (config firwmare)
  template:
    src: config-rpi4.txt.j2  
    dest: /var/tftpboot/config.txt
    mode: 0744

- name: rPi4 - Modification du fichier cmdline.txt (config init)
  template:
    src: cmdline.txt.j2
    dest: /var/tftpboot/cmdline.txt
    mode: 0744

- name: rPi4 - Installation des fichiers d'overlay pour l'écran LCD     
  copy: 
    src: "{{ item.path }}/{{ item.name }}"      
    dest: "/var/tftpboot/overlays/{{ item.name }}"
    mode: 0744
  with_items:
    - { name: "mhs35.dtbo", path: "{{ role_path }}/files/overlays" }
    - { name: "mhs35-overlay.dtb", path: "{{ role_path }}/files/overlays" }
