name: Build linux-virt kernel

runs:
  using: composite  

  steps:
    - name: Prepare the environment and build
      shell: sh
      run: |
        # Download aports sources
        wget https://gitlab.alpinelinux.org/alpine/aports/-/archive/master/aports-master.tar.bz2
        tar xjf aports-master.tar.bz2

        cd "aports-master/main/linux-lts"

        # Patch the config file (remove undesired archs)
        cp "virt.x86_64.config" "safecor-virt.x86_64.config"
        sed -i '/[[:space:]]*lts\..*\.config/d' APKBUILD
        sed -i '/virt\..*\.config/d' APKBUILD
        #sed -i 's/virt\.x86_64\.config/safecor-virt.x86_64.config/g' APKBUILD

        echo "CONFIG_HID_GENERIC=m" >> safecor-virt.x86_64.config
        echo "CONFIG_HID_MULTITOUCH=m" >> safecor-virt.x86_64.config
        echo "CONFIG_INPUT_TOUCHSCREEN=y" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_HID=m" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_SERIAL=m" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_SERIAL_GENERIC=y" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_SERIAL_FTDI_SIO=m" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_SERIAL_PL2303=m" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_SERIAL_CP210X=m" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_SERIAL_CH341=m" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_SERIAL_KEYSPAN=m" >> safecor-virt.x86_64.config
        echo "CONFIG_USB_ACM=m" >> safecor-virt.x86_64.config

        # Update permissions
        cd "$GITHUB_WORKSPACE/"
        sudo chown -R builder:builder "aports-master"

        # Build the package
        cd "aports-master/main/linux-lts"
        sudo -u builder FLAVOR=safecor-virt abuild checksum
        sudo -u builder FLAVOR=safecor-virt abuild -r

        # After building the kernel we have to build the xtables-addons-safecor-virt
        #cd "$GITHUB_WORKSPACE/aports-master/main/xtables-addons-lts"

        # Patch APKBUILD
        #sed -i \
        #-e 's|^pkgname=xtables-addons-lts$|pkgname=xtables-addons-safecor-virt|' \
        #-e 's|^_name=${pkgname%-*}$|_name=xtables-addons|' \
        #-e 's|^_flavor=${pkgname##*-}$|_flavor=safecor-virt|' \
        #APKBUILD

        #sudo -u builder FLAVOR=safecor-virt abuild checksum
        #sudo -u builder FLAVOR=safecor-virt abuild -r

    - name: Upload the packages
      uses: actions/upload-artifact@v4
      with:
        name: safecor-virt-x86_64
        path: /home/builder/packages/main/x86_64/*.apk
