name: Build all packages
 
on:
  workflow_dispatch:
    inputs:
      force-all:
        description: "Build all"
        required: false
        type: 'boolean'
        default: 'false'
      force-apps:
        description: "Build all apps"
        required: false
        type: 'boolean'
        default: 'false'
      force-libs:
        description: "Build all libs"
        required: false
        type: 'boolean'
        default: 'false'
      force-py3-paho-mqtt2:
        description: "Build py3-paho-mqtt2"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-alpine-iso:
        description: "Build alpine-iso"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-virt-kernel:
        description: "Build safecor-virt kernel"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-virt-iso:
        description: "Build safecor-virt ISO"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-container-debian:
        description: "Build container-debian"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-core:
        description: "Build core"
        required: false
        type: 'boolean'
        default: 'false'      
      force-safecor-diag:
        description: "Build diag"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-diag-iso:
        description: "Build diag ISO"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-hardening:
        description: "Build hardening"
        required: false
        type: 'boolean'
        default: 'false'  
      force-safecor-tests:
        description: "Build tests"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-tests-iso:
        description: "Build tests ISO"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-gui-base:
        description: "Build gui-base"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-lib:
        description: "Build lib"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-sys-gui:
        description: "Build sys-gui"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-sys-usb:
        description: "Build sys-usb"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-splash:
        description: "Build splash"
        required: false
        type: 'boolean'
        default: 'false'
      force-safecor-syslog:
        description: "Build syslog"
        required: false
        type: 'boolean'
        default: 'false'
      force-xtables-addons-safecor-virt:
        description: "Build xtables addons for Safecor virt"
        required: false
        type: 'boolean'
        default: 'false'
  push:
    branches:
      - "**"
    paths:
      - "setup/packages/safecor/**"
      - "python/**"

jobs:  
  detect-changes:
    name: Detect changed packages
    runs-on: ubuntu-latest
    outputs:
      pkg-py3-paho-mqtt2: ${{ steps.detect.outputs.py3-paho-mqtt2 }}
      pkg-safecor-alpine-iso: ${{ steps.detect.outputs.safecor-alpine-iso }}
      pkg-safecor-container-debian: ${{ steps.detect.outputs.safecor-container-debian }}
      pkg-safecor-core: ${{ steps.detect.outputs.safecor-core }}
      pkg-safecor-diag: ${{ steps.detect.outputs.safecor-diag }}
      pkg-safecor-gui-base: ${{ steps.detect.outputs.safecor-gui-base }}
      pkg-safecor-hardening: ${{ steps.detect.outputs.safecor-hardening }}
      pkg-safecor-lib: ${{ steps.detect.outputs.safecor-lib }}      
      pkg-safecor-sys-gui: ${{ steps.detect.outputs.safecor-sys-gui }}
      pkg-safecor-sys-usb: ${{ steps.detect.outputs.safecor-sys-usb }}
      pkg-safecor-syslog: ${{ steps.detect.outputs.safecor-syslog }}
      pkg-safecor-splash: ${{ steps.detect.outputs.safecore-splash }}
      pkg-xtables-addons-safecor-virt: ${{ steps.detect.outputs.xtables-addons-safecor-virt }}
      app-diag: ${{ steps.detect.outputs.app-diag }}      
      app-lib: ${{ steps.detect.outputs.app-lib }}
      app-tests: ${{ steps.detect.outputs.app-tests }}
            
    steps:
      - uses: actions/checkout@v4
      - name: Detect changed components
        id: detect
        run: |
          echo "Detecting changes..."
          declare -A paths=(
            [py3-paho-mqtt2]="setup/packages/safecor/py3-paho-mqtt2/"
            [safecor-alpine-iso]="setup/packages/safecor/safecor-alpine-iso/"
            [safecor-alpine-virt-kernel]="setup/packages/safecor/safecor-alpine-virt/"
            [safecor-container-debian]="setup/packages/safecor/py3-paho-mqtt2/"
            [safecor-core]="setup/packages/safecor/safecor-core/"
            [safecor-diag]="setup/packages/safecor/safecor-diag/"
            [safecor-gui-base]="setup/packages/safecor/safecor-gui-base/"
            [safecor-hardening]="setup/packages/safecor/safecor-hardening/"
            [safecor-lib]="setup/packages/safecor/safecor-lib/"
            [safecor-sys-gui]="setup/packages/safecor/safecor-sys-gui/"
            [safecor-sys-usb]="setup/packages/safecor/safecor-sys-usb/"
            [safecor-syslog]="setup/packages/safecor/safecor-syslog/"
            [safecor-splash]="setup/packages/safecor/safecor-splash/"
            [xtables-addons-safecor-virt]="setup/packages/safecor/xtables-addons-safecor-virt"
            [app-diag]="python/diag/"            
            [app-lib]="python/lib/"
            [app-tests]="python/tests/"
          )

          for key in "${!paths[@]}"; do
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
              | grep "^${paths[$key]}"; then
              echo "$key=true" >> $GITHUB_OUTPUT
            else
              echo "$key=false" >> $GITHUB_OUTPUT
            fi
          done

  prepare:
    runs-on: ubuntu-latest
    needs: detect-changes
    outputs:
      check-py3-paho-mqtt2: ${{ steps.check-py3-paho-mqtt2.outputs.do_build }}
      check-safecor-lib: ${{ steps.check-safecor-lib.outputs.do_build }}
      check-safecor-alpine-virt-kernel: ${{ steps.check-safecor-alpine-virt-kernel.outputs.do_build }}
      check-safecor-alpine-virt-iso: ${{ steps.check-safecor-alpine-virt-iso.outputs.do_build }}
      check-safecor-alpine-iso: ${{ steps.check-safecor-alpine-iso.outputs.do_build }}
      check-safecor-container-debian: ${{ steps.check-safecor-container-debian.outputs.do_build }}
      check-safecor-core: ${{ steps.check-safecor-core.outputs.do_build }}
      check-safecor-hardening: ${{ steps.check-safecor-hardening.outputs.do_build }}
      check-safecor-sys-gui: ${{ steps.check-safecor-sys-gui.outputs.do_build }}
      check-safecor-sys-usb: ${{ steps.check-safecor-sys-usb.outputs.do_build }}
      check-safecor-gui-base: ${{ steps.check-safecor-gui-base.outputs.do_build }}
      check-safecor-syslog: ${{ steps.check-safecor-syslog.outputs.do_build }}
      check-safecor-splash: ${{ steps.check-safecor-splash.outputs.do_build }}
      check-app-tests: ${{ steps.check-app-tests.outputs.do_build }}
      check-iso-tests: ${{ steps.check-app-tests.outputs.do_build }}
      check-app-diag: ${{ steps.check-app-diag.outputs.do_build }}      
      check-iso-diag: ${{ steps.check-app-diag.outputs.do_build }}
      check-xtables-addons-safecor-virt: ${{ steps.check-xtables-addons-safecor-virt.outputs.do_build }}
    steps:
      - id: check-py3-paho-mqtt2 
        name: check-py3-paho-mqtt2 
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-py3-paho-mqtt2 }}
          FORCE: ${{ github.event.inputs.force-py3-paho-mqtt2 }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' || $FORCE_LIBS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-lib
        name: check-safecor-lib
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-lib }}
          FORCE: ${{ github.event.inputs.force-safecor-lib }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' || $FORCE_LIBS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-alpine-virt-kernel
        name: check-safecor-alpine-virt-kernel
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-alpine-virt-kernel }}
          FORCE: ${{ github.event.inputs.force-safecor-virt-kernel }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-alpine-virt-iso
        name: check-safecor-alpine-virt-iso
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-alpine-virt-iso }}
          FORCE: ${{ github.event.inputs.force-safecor-virt-iso }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-alpine-iso
        name: check-safecor-alpine-iso
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-alpine-iso }}
          FORCE: ${{ github.event.inputs.force-safecor-alpine-iso }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-container-debian
        name: check-safecor-container-debian
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-container-debian }}
          FORCE: ${{ github.event.inputs.force-safecor-container-debian }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-core
        name: check-safecor-core
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-core }}
          FORCE: ${{ github.event.inputs.force-safecor-core }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-hardening
        name: check-safecor-hardening
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-hardening }}
          FORCE: ${{ github.event.inputs.force-safecor-hardening }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}             
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}       
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-syslog
        name: check-safecor-syslog
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-syslog }}
          FORCE: ${{ github.event.inputs.force-safecor-syslog }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}             
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}       
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-sys-gui
        name: check-safecor-sys-gui
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-sys-gui }}
          FORCE: ${{ github.event.inputs.force-safecor-sys-gui }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi        
      - id: check-safecor-sys-usb
        name: check-safecor-sys-usb
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-sys-usb }}
          FORCE: ${{ github.event.inputs.force-safecor-sys-usb }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-gui-base
        name: check-safecor-gui-base
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-gui-base }}
          FORCE: ${{ github.event.inputs.force-safecor-gui-base }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-safecor-splash
        name: check-safecor-splash
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-safecor-splash }}
          FORCE: ${{ github.event.inputs.force-safecor-splash }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-app-tests
        name: check-app-tests
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-app-tests }}
          FORCE: ${{ github.event.inputs.force-safecor-tests }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi
      - id: check-app-diag
        name: check-app-diag
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-app-diag }}
          FORCE: ${{ github.event.inputs.force-safecor-diag }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
          FORCE_APPS: ${{ github.event.inputs.force-apps }}
          FORCE_LIBS: ${{ github.event.inputs.force-libs }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi 
      - id: check-iso-diag
        name: check-iso-diag
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-app-diag }}
          FORCE: ${{ github.event.inputs.force-safecor-diag }} || ${{ github.event.inputs.force-safecor-diag-iso }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' || $FORCE_APPS == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi     
      - id: check-xtables-addons-safecor-virt
        name: check-xtables-addons-safecor-virt
        env:
          PKG_CHANGED: ${{ needs.detect-changes.outputs.pkg-xtables-addons-safecor-virt }}
          FORCE: ${{ github.event.inputs.force-xtables-addons-safecor-virt }}
          FORCE_ALL: ${{ github.event.inputs.force-all }}
        run: |          
          if [[ $PKG_CHANGED == 'true' || $FORCE == 'true' || $FORCE_ALL == 'true' ]]; then 
            echo "do_build=true" >> $GITHUB_OUTPUT
          else 
            echo "do_build=false" >> $GITHUB_OUTPUT
          fi      
          

  build-py3-paho-mqtt2:
    needs: [ prepare ]
    if: |
      needs.prepare.outputs.check-py3-paho-mqtt2 == 'true' ||
      needs.prepare.outputs.check-safecor-lib == 'true' ||
      needs.prepare.outputs.check-safecor-core == 'true' ||
      needs.prepare.outputs.check-safecor-sys-gui == 'true' ||
      needs.prepare.outputs.check-safecor-sys-usb == 'true' ||
      needs.prepare.outputs.check-safecor-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/py3-paho-mqtt2
          artifact-name: py3-paho-mqtt2

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/
          
  build-safecor-lib:
    needs: [ prepare, build-py3-paho-mqtt2 ]
    if: | 
      needs.prepare.outputs.check-safecor-lib == 'true' || 
      needs.prepare.outputs.check-safecor-core == 'true' ||     
      needs.prepare.outputs.check-safecor-sys-gui == 'true' ||
      needs.prepare.outputs.check-safecor-sys-usb == 'true' ||
      needs.prepare.outputs.check-safecor-gui-base == 'true' ||
      needs.prepare.outputs.check-safecor-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-lib
          artifact-name: safecor-lib

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-alpine-virt-kernel:
    needs: [ prepare ]
    if: |     
      needs.prepare.outputs.check-safecor-alpine-virt-kernel == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build kernel package
        uses: ./.github/actions/build-kernel         

      - name: Publish kernel package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/main/x86_64/ # The package comes from aports    

  build-xtables-addons-safecor-virt:
    needs: [ prepare ]
    if: | 
      needs.prepare.outputs.check-safecor-alpine-virt-kernel == 'true' ||
      needs.prepare.outputs.check-xtables-addons-safecor-virt == 'true' 
    
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build the package
        shell: sh
        run: |
          # Download aports sources
          wget https://gitlab.alpinelinux.org/alpine/aports/-/archive/master/aports-master.tar.bz2
          tar xjf aports-master.tar.bz2

          cd "aports-master/main/xtables-addons-lts"

          # Patch APKBUILD
          sed -i \
          -e 's|^pkgname=.*|pkgname=xtables-addons-safecor-virt|' \
          -e 's|^_name=.*|_name=xtables-addons|' \
          -e 's|^_flavor=.*|_flavor=safecor-virt|' \
          APKBUILD

          # Update permissions
          cd "$GITHUB_WORKSPACE/"
          sudo chown -R builder:builder "aports-master"

          cd "aports-master/main/xtables-addons-lts"
          sudo -u builder FLAVOR=safecor-virt abuild checksum
          sudo -u builder FLAVOR=safecor-virt abuild -r  

      - name: Publish kernel addons package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/main/x86_64/ # The package comes from aports    

  build-safecor-virt-iso:
    needs: [ prepare ]
    if: |
      needs.prepare.outputs.check-safecor-alpine-virt-iso == 'true'
      
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}

      - name: Build and publish ISO
        uses: ./.github/actions/build-and-publish-iso
        with:
          package-name: safecor-virt
          privkey: ${{ secrets.DEPLOY_KEY }}

  build-alpine-iso:
    needs: [ prepare ]
    if: | 
      needs.prepare.outputs.check-safecor-alpine-iso == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-alpine-iso
          artifact-name: safecor-alpine-iso

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/  

  build-lxc-container-debian:
    needs: [ prepare ]
    if: |
      false &&
      needs.prepare.outputs.check-safecor-container-debian == 'true'
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout sources 
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: sh
        run: |
          sudo apt update
          sudo apt install lxc lxc-templates liblxc-common iptables

      - name: Create generic Debian container 
        env:
          pkgname: lxc-container-debian
          srcdir: ${{ github.workspace }}/src
          distro: debian
          release: bookworm
          arch: amd64
          variant: default
        shell: sh         
        run: |
          # Create the container 
          sudo lxc-create -n "$pkgname" -t download -P "$srcdir" -- --dist $distro --release $release --arch $arch --variant $variant
          
          # Remove network configuration
          sudo sed -i 's/^lxc\.net/#&/' "$srcdir/$pkgname"/config
          
          # Stop the container
          # sudo lxc-stop "$pkgname"

          # Create an archive
          echo Compressing the image...
          sudo tar cjf "$pkgname".tar.bz2 -C "$srcdir" .
          echo Compression finished

          # Compress archive
          # sudo bzip2 "$pkgname".tar

      - name: Publish archive
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: lxc-container-debian.tar.bz2
          container: false

  build-container-debian:
    needs: [ prepare ]
    if: | 
      needs.prepare.outputs.check-safecor-container-debian == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-container-debian
          artifact-name: safecor-container-debian

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-safecor-core:
    needs: [ prepare ]
    if: |
      needs.prepare.outputs.check-safecor-core == 'true' ||
      needs.prepare.outputs.check-safecor-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-core
          artifact-name: safecor-core      

      - name: Publish packages
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-safecor-hardening:
    needs: [ prepare ]
    if: |
      needs.prepare.outputs.check-safecor-hardening == 'true' ||
      needs.prepare.outputs.check-safecor-core == 'true' ||
      needs.prepare.outputs.check-safecor-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-hardening
          artifact-name: safecor-hardening

      - name: Publish packages
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-safecor-syslog:
    needs: [ prepare ]
    if: |
      needs.prepare.outputs.check-safecor-syslog == 'true' ||
      needs.prepare.outputs.check-safecor-core == 'true' ||
      needs.prepare.outputs.check-safecor-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-syslog
          artifact-name: safecor-syslog

      - name: Publish packages
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-safecor-splash:
    needs: [ prepare ]
    if: |
      needs.prepare.outputs.check-safecor-splash == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-splash
          artifact-name: safecor-splash

      - name: Publish packages
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-safecor-sys-gui:
    needs: [ prepare, build-safecor-lib ]
    if: |
      needs.prepare.outputs.check-safecor-sys-gui == 'true' ||
      needs.prepare.outputs.check-safecor-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-sys-gui
          artifact-name: safecor-sys-gui

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-safecor-sys-usb:
    needs: [ prepare, build-safecor-lib ]
    if: |
      needs.prepare.outputs.check-safecor-sys-usb == 'true' ||
      needs.prepare.outputs.check-safecor-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}      
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-sys-usb
          artifact-name: safecor-sys-usb

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-safecor-gui-base:
    needs: [ prepare, build-safecor-lib ]
    if: |
      needs.prepare.outputs.check-safecor-gui-base == 'true' ||
      needs.prepare.outputs.check-safecor-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}     
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-gui-base
          artifact-name: safecor-gui-base

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-app-tests:
    #needs: [ prepare, build-safecor-lib, build-safecor-core, build-safecor-sys-gui, build-safecor-sys-usb, build-safecor-gui-base ]
    needs: [ prepare ]
    if: needs.prepare.outputs.check-app-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}     
 
      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-tests-gui
          artifact-name: safecor-tests-gui

      - name: Publish GUI package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-tests
          artifact-name: safecor-tests

      - name: Publish main package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-app-diag:
    needs: [ prepare ]
    if: needs.prepare.outputs.check-app-diag == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}

      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          working-dir: setup/packages/safecor/safecor-diag
          artifact-name: safecor-diag

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          privkey: ${{ secrets.DEPLOY_KEY }}
          filepath: /home/builder/packages/safecor/x86_64/

  build-iso-diag:
    needs: [ prepare, build-app-diag ]
    if: |
      needs.prepare.outputs.check-app-diag == 'true' ||
      needs.prepare.outputs.check-iso-diag == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}

      - name: Build and publish ISO
        uses: ./.github/actions/build-and-publish-iso
        with:
          package-name: diag
          privkey: ${{ secrets.DEPLOY_KEY }}

  build-iso-tests:
    needs: [ prepare, build-app-tests ]
    if: |
      needs.prepare.outputs.check-app-tests == 'true' ||
      needs.prepare.outputs.check-iso-tests == 'true'
    runs-on: ubuntu-latest
 
    container:
      image: alpine:3.21
 
    steps:      
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
        with:
          abuild-key: ${{ secrets.ABUILD_PRIVATE_KEY }}

      - name: Build and publish ISO
        uses: ./.github/actions/build-and-publish-iso
        with:
          package-name: tests
          privkey: ${{ secrets.DEPLOY_KEY }}